include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.11.0

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"

# NOTE(douglasduteil): No install :(
# sharing the node_modules is too slow...
Install:
  rules:
    - when: never

# NOTE(douglasduteil): No lint :(
Lint:
  rules:
    - when: never

# NOTE(douglasduteil): No test :(
Test:
  rules:
    - when: never

# NOTE(douglasduteil): use custom build job
# The website it statically built with React Scripts
# Here we manually reuse the `build` dir in Dockerfile
Build:
  needs: []
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - .cache
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - yarn --frozen-lockfile --prefer-offline
    - yarn build
  variables:
    VERSION: ${CI_COMMIT_SHORT_SHA}
  artifacts:
    expire_in: 1 day
    paths:
      - build

# NOTE(julienbouquillon): use custom register job
# By default, kosko-charts use a "/app" for docker images names
# TODO: discuss
Register image:
  extends: .autodevops_register_image
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/app
